import type { Exercise } from './types';

/**
 * Bibliothèque d'exercices d'orthophonie du MVP.
 *
 * Chaque exercice est déclaratif : id, trouble cible, compétence, difficulté,
 * pré-requis. Le `selectNextExercise` utilise ces métadonnées pour proposer
 * le bon exercice à l'enfant selon son profil et son historique.
 */

export const ORTHOPHONIC_EXERCISES: Exercise[] = [
  // === DYSLEXIE ===
  {
    id: 'dys-phono-syllabes-1',
    name: 'Je compte les syllabes',
    description: 'Écoute un mot et dis combien il a de syllabes.',
    trouble: 'dyslexie',
    competency: 'conscience syllabique',
    difficulty: 1,
    prerequisites: [],
    estimatedMinutes: 4,
  },
  {
    id: 'dys-phono-fusion-1',
    name: 'Fusion de sons',
    description: 'Assemble deux sons pour former une syllabe. Par exemple : [b] + [a] = "ba".',
    trouble: 'dyslexie',
    competency: 'fusion phonémique',
    difficulty: 2,
    prerequisites: ['dys-phono-syllabes-1'],
    estimatedMinutes: 5,
  },
  {
    id: 'dys-lecture-cv',
    name: 'Lecture de syllabes CV',
    description: 'Lis des syllabes consonne-voyelle : ba, to, mi, lu…',
    trouble: 'dyslexie',
    competency: 'décodage syllabique',
    difficulty: 2,
    prerequisites: ['dys-phono-fusion-1'],
    estimatedMinutes: 5,
  },
  {
    id: 'dys-lecture-pseudos',
    name: 'Lecture de pseudo-mots',
    description: 'Lis des mots inventés : lovu, tarpi, kromane…',
    trouble: 'dyslexie',
    competency: 'décodage pur',
    difficulty: 3,
    prerequisites: ['dys-lecture-cv'],
    estimatedMinutes: 6,
  },
  {
    id: 'dys-lecture-fluence',
    name: 'Lecture en chaîne',
    description: 'Lis une suite de mots le plus vite possible, sans te tromper.',
    trouble: 'dyslexie',
    competency: 'fluence de lecture',
    difficulty: 4,
    prerequisites: ['dys-lecture-pseudos'],
    estimatedMinutes: 7,
  },

  // === DYSORTHOGRAPHIE ===
  {
    id: 'ortho-copie-flash',
    name: 'Copie éclair',
    description: 'Regarde un mot pendant 3 secondes, il disparaît, tu le réécris.',
    trouble: 'dysorthographie',
    competency: 'mémoire orthographique',
    difficulty: 2,
    prerequisites: [],
    estimatedMinutes: 5,
  },
  {
    id: 'ortho-dictee-mots',
    name: 'Dictée de mots',
    description: "Écris les mots qu'on te dit. Pas besoin de phrases.",
    trouble: 'dysorthographie',
    competency: 'orthographe lexicale',
    difficulty: 3,
    prerequisites: [],
    estimatedMinutes: 6,
  },
  {
    id: 'ortho-regles-sonores',
    name: 'Règles qui changent tout',
    description: '"m" devant "p" ou "b" devient "mm" ? Découvre les règles qui changent l\'écriture.',
    trouble: 'dysorthographie',
    competency: 'règles d\'orthographe',
    difficulty: 3,
    prerequisites: ['ortho-copie-flash'],
    estimatedMinutes: 5,
  },
  {
    id: 'ortho-homophones',
    name: 'A ou à ? Est ou et ?',
    description: 'Choisis le bon mot entre deux qui se prononcent pareil.',
    trouble: 'dysorthographie',
    competency: 'homophones grammaticaux',
    difficulty: 4,
    prerequisites: ['ortho-regles-sonores'],
    estimatedMinutes: 6,
  },

  // === DYSCALCULIE ===
  {
    id: 'dysc-subitize-flash',
    name: 'Compte éclair',
    description: 'Combien il y a d\'objets ? Sans les compter un par un.',
    trouble: 'dyscalculie',
    competency: 'subitisation',
    difficulty: 1,
    prerequisites: [],
    estimatedMinutes: 4,
  },
  {
    id: 'dysc-transcodage',
    name: 'Du nombre au mot',
    description: 'On te montre 12, tu dis "douze". On te dit "quinze", tu écris 15.',
    trouble: 'dyscalculie',
    competency: 'transcodage chiffre/mot',
    difficulty: 2,
    prerequisites: ['dysc-subitize-flash'],
    estimatedMinutes: 5,
  },
  {
    id: 'dysc-droite-numerique',
    name: 'La droite des nombres',
    description: 'Place le nombre au bon endroit sur la droite.',
    trouble: 'dyscalculie',
    competency: 'représentation numérique',
    difficulty: 3,
    prerequisites: ['dysc-transcodage'],
    estimatedMinutes: 5,
  },
  {
    id: 'dysc-faits-addition',
    name: 'Les additions de tête',
    description: 'Calcule des petites additions de plus en plus vite.',
    trouble: 'dyscalculie',
    competency: 'faits numériques (addition)',
    difficulty: 3,
    prerequisites: ['dysc-transcodage'],
    estimatedMinutes: 6,
  },
  {
    id: 'dysc-faits-soustraction',
    name: 'Les soustractions de tête',
    description: 'Calcule des petites soustractions de plus en plus vite.',
    trouble: 'dyscalculie',
    competency: 'faits numériques (soustraction)',
    difficulty: 3,
    prerequisites: ['dysc-faits-addition'],
    estimatedMinutes: 6,
  },

  // === ARTICULATION / LANGAGE ORAL ===
  {
    id: 'art-paires-minimales',
    name: 'Paires de mots qui s\'entendent presque pareil',
    description: '"Poule" ou "boule" ? Écoute bien et choisis.',
    trouble: 'articulation',
    competency: 'discrimination phonologique',
    difficulty: 2,
    prerequisites: [],
    estimatedMinutes: 5,
  },
  {
    id: 'art-repetition',
    name: 'Répète après LUMO',
    description: 'LUMO dit un mot difficile, tu le répètes.',
    trouble: 'articulation',
    competency: 'reproduction phonologique',
    difficulty: 3,
    prerequisites: ['art-paires-minimales'],
    estimatedMinutes: 5,
  },
  {
    id: 'art-denomination',
    name: 'Comment ça s\'appelle ?',
    description: 'Une image apparaît, tu dois dire le mot le plus vite possible.',
    trouble: 'articulation',
    competency: 'accès lexical',
    difficulty: 3,
    prerequisites: [],
    estimatedMinutes: 6,
  },

  // === MÉMOIRE DE TRAVAIL ===
  {
    id: 'mem-sequences-couleurs',
    name: 'La suite des couleurs',
    description: 'Répète la séquence de couleurs montrée par LUMO.',
    trouble: 'memoire',
    competency: 'mémoire visuo-spatiale',
    difficulty: 2,
    prerequisites: [],
    gameSlug: 'simon-lumo',
    estimatedMinutes: 5,
  },
  {
    id: 'mem-chiffres-avant',
    name: 'Répète les chiffres',
    description: 'LUMO dit une suite de chiffres, tu la répètes dans le même ordre.',
    trouble: 'memoire',
    competency: 'empan mnésique direct',
    difficulty: 3,
    prerequisites: ['mem-sequences-couleurs'],
    estimatedMinutes: 5,
  },
  {
    id: 'mem-chiffres-envers',
    name: 'Les chiffres à l\'envers',
    description: 'LUMO dit une suite de chiffres, tu la répètes à l\'envers.',
    trouble: 'memoire',
    competency: 'empan mnésique inverse',
    difficulty: 4,
    prerequisites: ['mem-chiffres-avant'],
    estimatedMinutes: 6,
  },
];
